fix: example requires numpy to be imported
A user copying and pasting the existing sample will hit the following error. 
```
NameError: name 'numpy' is not defined
```

This is avoidable by including import numpy in the example.